name: value_layout_builder
description: A LayoutBuilder with an extra value. It's useful when you want to build a widget with a value computed during layout.
version: 0.3.1
homepage: https://github.com/letsar/value_layout_builder

environment:
  sdk: '>=2.14.0 <3.0.0'
  flutter: '>=1.24.0-10.2.pre'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
